### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Gul7333** [apk-editor/APK-Explorer-Editor#22]
App Name: APK Explorer & Editor
Package Name: com.apk.editor
App Version: v0.22
SDK Version: 29

Crash Report

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.EditText.getVisibility()' on a null object reference
	at com.apk.editor.MainActivity.onBackPressed(:4)
	at android.app.Activity.onKeyUp(Activity.java:3656)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2833)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3973)
	at u.e.f(Unknown Source:0)
	at e0.d.b(Unknown Source:10)
	at u.e.dispatchKeyEvent(Unknown Source:18)
	at b.c.dispatchKeyEvent(Unknown Source:10)
	at b.f$d.dispatchKeyEvent(:1)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:371)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5645)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5508)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5064)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5030)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5038)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5227)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5064)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5030)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5038)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5064)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5030)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5203)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5368)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:7684)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:507)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Steps to reproduce the issue: I opened a app Android system..then pressed back ..it asked me I want to save project...I declined and deleted the project and pressed back and came back to apps...then again pressed back to exit .then..this crash showed..

**Comment by apk-editor** [comment]
@Gul7333 
I hope these kind of issues are fixed as of [v0.25](https://github.com/apk-editor/APK-Explorer-Editor/releases/tag/v0.25). So, closing this issue. If not, feel free to reopen it. Thanks and sorry for the long delay in responding to it.

**Comment by edsongaiolas** [comment]
Tá com crash esse aplicativo guando click no apks simples fecha App Name: APK Explorer & Editor
Package Name: com.apk.editor
App Version: v0.35
SDK Version: 29

==========
 Stacktrace
==========

java.lang.NullPointerException: Attempt to get length of null array
	at h.b(r8-map-id-19e6c021ca0585ca1cb16b56614671c34533d451f1a5e2f4b65c8b02e3656da0:677)
	at oz0.run(r8-map-id-19e6c021ca0585ca1cb16b56614671c34533d451f1a5e2f4b65c8b02e3656da0:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)


Steps to reproduce this issue:
