### ISSUE TITLE
Permanent crash on launch. Reinstall and clear cache/data have no effect

### ISSUE THREAD

**Issue by bluechipps** [apk-editor/APK-Explorer-Editor#42]
Everything was working fine. I tested modifying and rebuilding a couple apps with no problem. Just all of a sudden would start crashing right after the splash/loading activity. Here is the logcat. I left out the pages of "unknown manifest element" prior to the ones seen here.

```
02-17 12:09:03.566 15545 15576 W PackageParser: Unknown element under <manifest>: queries at /product/priv-app/SafetyHubPrebuilt/SafetyHubPrebuilt.apk Binary XML file line #66
02-17 12:09:03.575 15545 15576 W PackageParser: Unknown element under <manifest>: queries at /data/app/~~7UvVqcXJSfy2t8zay8MDyQ==/net.gsantner.markor-Fnz0ovtirWGnzg30cBQFYg==/base.apk Binary XML file line #42
02-17 12:09:03.578 15545 15576 W PackageParser: Unknown element under <manifest>: queries at /data/app/~~7UvVqcXJSfy2t8zay8MDyQ==/net.gsantner.markor-Fnz0ovtirWGnzg30cBQFYg==/base.apk Binary XML file line #42
--------- beginning of crash
02-17 12:09:03.582 15545 15576 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
02-17 12:09:03.582 15545 15576 E AndroidRuntime: Process: com.apk.editor, PID: 15545
02-17 12:09:03.582 15545 15576 E AndroidRuntime: java.lang.NullPointerException
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at java.util.Objects.requireNonNull(Objects.java:220)
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at l2.e.b(:2)
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at t0.y.a(:1)
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at s0.b.run(:3)
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
02-17 12:09:03.582 15545 15576 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
```

I do have a theory about what could have caused it. A few minutes prior to the start of the crashes, I uninstalled an app differently than I typically do. In an app management app I use, when I uninstalled I selected an option to "Keep data and signatures". I believe afterwards I tried to reinstall using my modified version of the same app. This is just a theory.

**Comment by bluechipps** [comment]
Had some spare time tonight so I did some debugging and tracked it down far enough to create a work around. Not sure if there is a better solution but AEE sees to be back to its old self again.

I think I was right about my theory. Will see if I can reproduce it tomorrow to confirm. Could have to do with a package installer flag DELETE_KEEP_DATA.

**Comment by bluechipps** [comment]
Resolved
