### ISSUE TITLE
Exploring app

### ISSUE THREAD

**Issue by islam2hamy** [apk-editor/APK-Explorer-Editor#7]
FATAL EXCEPTION: AsyncTask #2
Process: com.apk.editor, PID: 2771
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6994)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1092)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.view.View.requestLayout(View.java:19810)
	at android.widget.TextView.checkForRelayout(TextView.java:7369)
	at android.widget.TextView.setText(TextView.java:4487)
	at android.widget.TextView.setText(TextView.java:4344)
	at android.widget.TextView.setText(TextView.java:4319)
	at android.app.ProgressDialog.setMessage(ProgressDialog.java:316)
	at b.b.a.i.j0.doInBackground(:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by islam2hamy** [comment]
Miui 11.0.2
Android 7.1.2

**Comment by apk-editor** [comment]
@islam2hamy 
Thanks for raising this issue.
Can you tell me when this crash happened? I mean upon trying to explore which application? If possible, can you attach the copy of the failed APK (you can export using AEE by long pressing) so that I can try to reproduce (and eventually fix) the issue here.
Thanks

**Comment by islam2hamy** [comment]
it hapend randomly

Any apk

**Comment by islam2hamy** [comment]
Try this

FlorisBoard (An open-source keyboard which respects your privacy. Currently in early-beta.) - https://f-droid.org/packages/dev.patrickgold.florisboard

**Comment by apk-editor** [comment]
@islam2hamy 
This issue should be fixed from next version. So, closing this issue. Feel free to reopen this issue, if you again faced this issue after v0.17 (not released yet). Thank You.
